name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["5.6", "7.2", "7.4", "8.0", "8.1"]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./php/Dockerfile --build-arg PHP_VERSION_ARG=${{ matrix.php_version }} --tag dock4/php:$(date +%s)
