name: Docker

on:
  schedule:
    - cron: '42 12 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["5.6", "7.2", "7.4", "8.0", "8.1"]
    permissions:
      contents: read
      packages: write

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/docker/login-action
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            suffix=-${{ matrix.php_version }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=raw,value=latest

      # https://github.com/docker/build-push-action
      # run: docker build . --file ./php/Dockerfile --build-arg PHP_VERSION_ARG=${{ matrix.php_version }} --tag dock4/php:$(date +%s)
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php/Dockerfile
          build-args: |
            PHP_VERSION_ARG=${{ matrix.php_version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
